# Generated by Django 5.2.5 on 2025-08-20 13:36

import Backendkadi.models.user
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameorder', models.CharField(max_length=50)),
                ('numTelephone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Le numéro doit contenir exactement 10 chiffres.')])),
                ('exactaddress', models.CharField(max_length=50)),
                ('command_type', models.CharField(choices=[('fassou', 'Fassou'), ('personalized', 'Personnalisée')], max_length=20)),
                ('model_type', models.CharField(choices=[('femme', 'femme'), ('homme', 'homme'), ('enfant', 'enfant')], max_length=20)),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('pending', 'En cours'), ('done', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FashionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('femme', 'femme'), ('homme', 'homme'), ('enfant', 'enfant')], max_length=20)),
                ('price_per_piece_for_client', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_piece_for_dropshipper', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('min_pieces_for_dropshipper', models.PositiveIntegerField()),
                ('totalquantity', models.PositiveIntegerField(default=10)),
                ('state', models.CharField(choices=[('accepted', 'Accepted'), ('waiting', 'Waiting'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Réduction visible par le client', max_digits=5)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('3XL', '3XL'), ('4XL', '4XL')], null=True)),
                ('color', models.CharField(choices=[('aliceblue', 'aliceblue'), ('antiquewhite', 'antiquewhite'), ('aqua', 'aqua'), ('aquamarine', 'aquamarine'), ('azure', 'azure'), ('beige', 'beige'), ('bisque', 'bisque'), ('black', 'black'), ('blanchedalmond', 'blanchedalmond'), ('blue', 'blue'), ('blueviolet', 'blueviolet'), ('brown', 'brown'), ('burlywood', 'burlywood'), ('cadetblue', 'cadetblue'), ('chartreuse', 'chartreuse'), ('chocolate', 'chocolate'), ('coral', 'coral'), ('cornflowerblue', 'cornflowerblue'), ('cornsilk', 'cornsilk'), ('crimson', 'crimson'), ('cyan', 'cyan'), ('darkblue', 'darkblue'), ('darkcyan', 'darkcyan'), ('darkgoldenrod', 'darkgoldenrod'), ('darkgray', 'darkgray'), ('darkgrey', 'darkgrey'), ('darkgreen', 'darkgreen'), ('darkkhaki', 'darkkhaki'), ('darkmagenta', 'darkmagenta'), ('darkolivegreen', 'darkolivegreen'), ('darkorange', 'darkorange'), ('darkorchid', 'darkorchid'), ('darkred', 'darkred'), ('darksalmon', 'darksalmon'), ('darkseagreen', 'darkseagreen'), ('darkslateblue', 'darkslateblue'), ('darkslategray', 'darkslategray'), ('darkslategrey', 'darkslategrey'), ('darkturquoise', 'darkturquoise'), ('darkviolet', 'darkviolet'), ('deeppink', 'deeppink'), ('deepskyblue', 'deepskyblue'), ('dimgray', 'dimgray'), ('dimgrey', 'dimgrey'), ('dodgerblue', 'dodgerblue'), ('firebrick', 'firebrick'), ('floralwhite', 'floralwhite'), ('forestgreen', 'forestgreen'), ('fuchsia', 'fuchsia'), ('gainsboro', 'gainsboro'), ('ghostwhite', 'ghostwhite'), ('gold', 'gold'), ('goldenrod', 'goldenrod'), ('gray', 'gray'), ('grey', 'grey'), ('green', 'green'), ('greenyellow', 'greenyellow'), ('honeydew', 'honeydew'), ('hotpink', 'hotpink'), ('indianred', 'indianred'), ('indigo', 'indigo'), ('ivory', 'ivory'), ('khaki', 'khaki'), ('lavender', 'lavender'), ('lavenderblush', 'lavenderblush'), ('lawngreen', 'lawngreen'), ('lemonchiffon', 'lemonchiffon'), ('lightblue', 'lightblue'), ('lightcoral', 'lightcoral'), ('lightcyan', 'lightcyan'), ('lightgoldenrodyellow', 'lightgoldenrodyellow'), ('lightgray', 'lightgray'), ('lightgrey', 'lightgrey'), ('lightgreen', 'lightgreen'), ('lightpink', 'lightpink'), ('lightsalmon', 'lightsalmon'), ('lightseagreen', 'lightseagreen'), ('lightskyblue', 'lightskyblue'), ('lightslategray', 'lightslategray'), ('lightslategrey', 'lightslategrey'), ('lightsteelblue', 'lightsteelblue'), ('lightyellow', 'lightyellow'), ('lime', 'lime'), ('limegreen', 'limegreen'), ('linen', 'linen'), ('magenta', 'magenta'), ('maroon', 'maroon'), ('mediumaquamarine', 'mediumaquamarine'), ('mediumblue', 'mediumblue'), ('mediumorchid', 'mediumorchid'), ('mediumpurple', 'mediumpurple'), ('mediumseagreen', 'mediumseagreen'), ('mediumslateblue', 'mediumslateblue'), ('mediumspringgreen', 'mediumspringgreen'), ('mediumturquoise', 'mediumturquoise'), ('mediumvioletred', 'mediumvioletred'), ('midnightblue', 'midnightblue'), ('mintcream', 'mintcream'), ('mistyrose', 'mistyrose'), ('moccasin', 'moccasin'), ('navajowhite', 'navajowhite'), ('navy', 'navy'), ('oldlace', 'oldlace'), ('olive', 'olive'), ('olivedrab', 'olivedrab'), ('orange', 'orange'), ('orangered', 'orangered'), ('orchid', 'orchid'), ('palegoldenrod', 'palegoldenrod'), ('palegreen', 'palegreen'), ('paleturquoise', 'paleturquoise'), ('palevioletred', 'palevioletred'), ('papayawhip', 'papayawhip'), ('peachpuff', 'peachpuff'), ('peru', 'peru'), ('pink', 'pink'), ('plum', 'plum'), ('powderblue', 'powderblue'), ('purple', 'purple'), ('red', 'red'), ('rosybrown', 'rosybrown'), ('royalblue', 'royalblue'), ('saddlebrown', 'saddlebrown'), ('salmon', 'salmon'), ('sandybrown', 'sandybrown'), ('seagreen', 'seagreen'), ('seashell', 'seashell'), ('sienna', 'sienna'), ('silver', 'silver'), ('skyblue', 'skyblue'), ('slateblue', 'slateblue'), ('slategray', 'slategray'), ('slategrey', 'slategrey'), ('snow', 'snow'), ('springgreen', 'springgreen'), ('steelblue', 'steelblue'), ('tan', 'tan'), ('teal', 'teal'), ('thistle', 'thistle'), ('tomato', 'tomato'), ('turquoise', 'turquoise'), ('violet', 'violet'), ('wheat', 'wheat'), ('white', 'white'), ('whitesmoke', 'whitesmoke'), ('yellow', 'yellow'), ('yellowgreen', 'yellowgreen')], max_length=20, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WilayaDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya_name', models.CharField(max_length=100, unique=True)),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mycustomorders/')),
                ('fashion_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_images', to='Backendkadi.customorder')),
            ],
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='models/')),
                ('fashion_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Backendkadi.fashionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='fashionmodel',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='Backendkadi.promocode'),
        ),
        migrations.AddField(
            model_name='fashionmodel',
            name='variants',
            field=models.ManyToManyField(related_name='fashion_models', to='Backendkadi.stockvariant'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='command_details',
            field=models.ManyToManyField(related_name='orders', to='Backendkadi.stockvariant'),
        ),
        migrations.AddField(
            model_name='customorder',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customorders_details', to='Backendkadi.wilayadelivery'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('couturiere', 'Couturière'), ('dropshipper', 'Dropshipper'), ('affiliate', 'Affilié'), ('client', 'Client')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('token_expiration', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.FileField(upload_to=Backendkadi.models.user.custom_upload_path)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Documents',
            },
        ),
        migrations.AddField(
            model_name='promocode',
            name='affiliate',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'affiliate'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'En cours'), ('done', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fashion_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Backendkadi.fashionmodel')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_orders', to='Backendkadi.promocode')),
                ('standard_command_details', models.ManyToManyField(related_name='orders_standard', to='Backendkadi.stockvariant')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='Backendkadi.wilayadelivery')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['client', 'dropshipper']}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dropshipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_link', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customorder',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Couturiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('is_accepted', models.BooleanField(default=False)),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreed_to_policy', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
