# Generated by Django 5.2.5 on 2025-09-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionmodel',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
