# Generated by Django 5.2.5 on 2025-08-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='initial_price',
        ),
    ]
