# Generated by Django 5.2.4 on 2025-09-19 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionmodel',
            name='fashion_model',
        ),
    ]
