# Generated by Django 5.2.5 on 2025-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0002_fashionmodel_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropshipper',
            name='is_accepted',
            field=models.BooleanField(),
        ),
    ]
