# Generated by Django 5.2.4 on 2025-08-08 18:55

import Backendkadi.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.FileField(upload_to=Backendkadi.models.user.custom_upload_path)),
                ('couturiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backendkadi.couturiere')),
                ('dropshipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Backendkadi.dropshipper')),
            ],
            options={
                'verbose_name_plural': 'User Documents',
            },
        ),
    ]
