# Generated by Django 5.2.5 on 2025-08-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0002_remove_customorder_initial_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fashionmodel',
            name='totalquantity',
        ),
    ]
