# Generated by Django 5.2.5 on 2025-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0003_remove_fashionmodel_totalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='model_type',
            field=models.CharField(choices=[('femme', 'femme'), ('homme', 'homme'), ('enfant', 'enfant')], max_length=20, null=True),
        ),
    ]
