# Generated by Django 5.2.5 on 2025-09-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0003_alter_dropshipper_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='couturiere',
            name='refused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dropshipper',
            name='refused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
