# Generated by Django 5.2.4 on 2025-08-08 19:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0003_userdocuments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couturiere',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='dropshipper',
            name='folder',
        ),
        migrations.AddField(
            model_name='userdocuments',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='couturiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Backendkadi.couturiere'),
        ),
        migrations.AlterField(
            model_name='userdocuments',
            name='dropshipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Backendkadi.dropshipper'),
        ),
    ]
