# Generated by Django 5.2.5 on 2025-08-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0004_alter_customorder_model_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorderimage',
            old_name='fashion_model',
            new_name='CustomOrder',
        ),
    ]
