# Generated by Django 5.2.4 on 2025-08-09 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0004_remove_couturiere_folder_remove_dropshipper_folder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdocuments',
            name='couturiere',
        ),
        migrations.RemoveField(
            model_name='userdocuments',
            name='dropshipper',
        ),
        migrations.AddField(
            model_name='userdocuments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
