# Generated by Django 5.2.5 on 2025-09-22 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0005_alter_dropshipper_is_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropshipperClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('address_exact', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('dropshipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Backendkadi.dropshipper')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_wilaya', to='Backendkadi.wilayadelivery')),
            ],
            options={
                'verbose_name': 'Client Dropshipper',
                'verbose_name_plural': 'Clients Dropshippers',
                'ordering': ['-date_creation'],
            },
        ),
    ]
