# Generated by Django 5.2.5 on 2025-08-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0005_rename_fashion_model_customorderimage_customorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorderimage',
            old_name='CustomOrder',
            new_name='customorder',
        ),
    ]
