# Generated by Django 5.2.5 on 2025-08-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0006_rename_customorder_customorderimage_customorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorderimage',
            old_name='customorder',
            new_name='fashion_model',
        ),
    ]
