# Generated by Django 5.2.5 on 2025-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0006_dropshipperclients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dropshipperclients',
            options={'verbose_name': 'Client Dropshipper', 'verbose_name_plural': 'Clients Dropshippers'},
        ),
        migrations.RemoveField(
            model_name='dropshipperclients',
            name='address_exact',
        ),
        migrations.RemoveField(
            model_name='dropshipperclients',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='dropshipperclients',
            name='numero_telephone',
        ),
        migrations.RemoveField(
            model_name='dropshipperclients',
            name='wilaya',
        ),
    ]
