# Generated by Django 5.2.5 on 2025-09-23 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0007_alter_dropshipperclients_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dropshipper_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='Backendkadi.dropshipperclients'),
        ),
    ]
