# Generated by Django 5.2.5 on 2025-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0007_rename_customorder_customorderimage_fashion_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('couturiere', 'Couturière'), ('dropshipper', 'Dropshipper'), ('affiliate', 'Affilié'), ('client', 'Client'), ('admin', 'Administrateur')], max_length=20),
        ),
    ]
