# Generated by Django 5.2.5 on 2025-08-25 15:37

import Backendkadi.models.socialAccountsLinkgroups
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountsLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être algérien (10 chiffres commençant par 05, 06 ou 07)', regex='^(05|06|07)\\d{8}$')])),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(), Backendkadi.models.socialAccountsLinkgroups.SocialAccountsLinkGroup.validate_instagram_url])),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(), Backendkadi.models.socialAccountsLinkgroups.SocialAccountsLinkGroup.validate_facebook_url])),
                ('group_dropshipping', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(), Backendkadi.models.socialAccountsLinkgroups.SocialAccountsLinkGroup.validate_whatsapp_group_url])),
                ('group_investissement', models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(), Backendkadi.models.socialAccountsLinkgroups.SocialAccountsLinkGroup.validate_whatsapp_group_url])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
