# Generated by Django 5.2.5 on 2025-08-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendkadi', '0009_socialaccountslinkgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='initial_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
