from django.urls import path
from .views import create_or_update_social_links
from . import views
urlpatterns = [
    path('updatesociallinks/', create_or_update_social_links, name='social-links-create-update'),
    path('ordersClientsDropshippers/', views.get_all_orders, name='admin-orders'),
    path('getAllDropshippers/', views.get_dropshippers_info, name='get_dropshippers_info'),
    path('wilayas/updateprixlivraison/', views.bulk_update_wilaya_prices, name='bulk-update-wilayas'),
    path('getallwilayaswithprices/', views.get_all_wilayas, name='get-all-wilayas'),
    path('refusedropshipper/<str:email>', views.refuse_dropshipper, name='refuse_dropshipper'),
    path('acceptdropshipper/<str:email>', views.accept_dropshipper, name='accept_dropshipper'),
    path('activatecomptedropshipper/<str:email>', views.activate_dropshipper_account_detailed, name='activate_dropshipper_account_detailed'),
    path('desactivatecomptedropshipper/<str:email>', views.deactivate_dropshipper_account, name='deactivate_dropshipper_account'),
    path('getallaffiliateinfos/', views.get_affiliates_info, name='get_affiliates_info'),
    path('generate-promo-code/', views.generate_promo_code_api, name='generate-promo-code'),
    path('most-demanded-models/', views.get_most_sold_models, name='get_most_sold_models'),
    path('GetMostActiveCouturiere/', views.get_most_active_couturiere, name='get_most_active_couturiere'),
    path('addNewAffilier/', views.add_new_affiliate, name='add_new_affiliate'),
    path('reworkwithaffiliate/<str:email>', views.rework_with_affiliate, name='rework_with_affiliate'),
    path('getmodelsnotaffectedtopromocode', views.get_models_not_affected_toaprmocode, name='get_models_not_affected_toaprmocode'),
    path('refusecommand/<str:command_type>/<str:command_code>/',views.refuse_command,name='refuse-command'),
    path('inprogressCommandstandard/<str:code_order>/', views.update_order_status_versinprogresspourcommandestandard, name='update_order_status_versinprogresspourcommandestandard'), 
    path('inprogressCommandcustom/<str:codeorder>/<str:new_price>/', views.update_custom_order_statusversinprogress, name='update_custom_order_statusversinprogress'),
    path('MakeStandardCommandDone/<str:model_code>/<str:order_code>/',views.make_standard_command_done,name='make_standard_command_done'),
    path('MakeCustomCommandDone/<str:ordercode>/', views.make_custom_command_done, name='make_custom_command_done'), 
    path('VerifiyIfVariantModelgreaterthanOrEqualToVariantQuantity/<str:model_code>/',views.verify_model_variants,name='verify_model_variants'),
    path('modifyModelToBeAbleToMakeTheOrderOfClient/<str:model_code>/',views.modify_model_variants,name='modify_model_variants'),
    path('listCouturieres', views.list_couturieres, name='list_couturieres'),
    path('updateCouturiereStatus/<int:id>/', views.update_couturiere_status, name='update-couturiere-status'),
    path('updateCouturiereActiveStatus/<int:id>/', views.update_couturiere_active_status, name='update-couturiere-active-status'), 
    path('getInfoModelCouturiereWaitingToBePublished',views.get_info_model_couturiere_waiting,name='get_info_model_waiting'),
    path('accept-model/', views.accept_fashion_model, name='accept_fashion_model'),
    path('RefuseModelCouturiere/<str:model_code>/',views.refuse_model_couturiere,name='refuse-model-couturiere'),
    path('addNewModelByAdmin/', views.add_new_model_by_admin, name='add-new-model-by-admin'),
    path('<str:model_code>/delete/', views.delete_fashion_model, name='delete-fashion-model'),
    path('createCommandefassou/', views.create_commande_fassou, name='create-commande-fassou'),
    path('getInfoCommandeFassou', views.getInfoCommandeFassou, name='get_info_commande_fassou'),
    path('makefassouCommandCompleted/<str:codeorder>/', views.make_fassou_command_completed, name='make_fassou_command_completed'),
    path('makefassouCommandrefused/<str:codeorder>/', views.make_fassou_command_refused, name='make_fassou_command_refused'),
    path('getmostActifAffilier', views.get_most_active_affiliate, name='get_most_active_affiliate'),
    path('gettotalbenificefromsalingproductspersonlaised&standardinmonth', views.get_total_benefit_from_saling_products_personalized_standard_in_month,name='get_total_benefit'),
    path('veriifyifweareabletomodifyamodel/<str:model_code>/',views.verify_if_we_are_able_to_modify_model,name='verify-model-modification'),
    path('chnageModelFromNotVisibleToAccepted/<str:model_code>/', views.change_model_from_not_visible_to_accepted,name='change_model_from_not_visible_to_accepted'),
    ]